using System.Globalization;
using System.Text;
using CCaaS.Application.Appointment;

namespace CCaaS.Api;

/// <summary>Dependency-free, printable appointment voucher renderer.</summary>
internal static class AppointmentVoucherPdf
{
    private const double PageWidth = 612;
    private const double PageHeight = 792;

    public static byte[] Create(AppointmentVoucherData voucher)
    {
        var pdf = new StringBuilder();
        Fill(pdf, 0, 0, PageWidth, PageHeight, "0.972 0.980 0.992");
        Fill(pdf, 0, 672, PageWidth, 120, "0.055 0.125 0.255");
        Fill(pdf, 0, 672, 10, 120, "0.055 0.690 0.705");
        Text(pdf, "CCAAS", 42, 746, 21, true, "1 1 1");
        Text(pdf, "AI VOICE CONTACT CENTER", 42, 724, 8, true, "0.565 0.835 0.890");
        Text(pdf, "APPOINTMENT VOUCHER", 330, 744, 16, true, "1 1 1");
        Text(pdf, "Confirmed booking document", 388, 723, 9, false, "0.790 0.835 0.910");

        Box(pdf, 36, 618, 540, 38, "0.900 0.980 0.945", "0.055 0.620 0.365");
        Text(pdf, "CONFIRMED", 52, 633, 11, true, "0.020 0.445 0.250");
        Text(pdf, $"Booking reference: {voucher.BookingReference}", 177, 633, 11, true, "0.055 0.125 0.255");

        Card(pdf, 36, 492, 258, 106, "CUSTOMER DETAILS");
        LabelValue(pdf, "Name", voucher.CustomerName, 52, 556, 112);
        LabelValue(pdf, "Contact", voucher.CustomerContact, 52, 530, 112);
        LabelValue(pdf, "Purpose", Short(voucher.Purpose ?? "General appointment", 38), 52, 504, 112);

        Card(pdf, 312, 492, 264, 106, "SERVICE PROVIDER");
        LabelValue(pdf, "Provider", Short(voucher.ProviderName, 30), 328, 556, 400);
        LabelValue(pdf, "Status", voucher.Status, 328, 530, 400);
        LabelValue(pdf, "Time zone", "UTC", 328, 504, 400);

        Card(pdf, 36, 340, 540, 130, "APPOINTMENT SCHEDULE");
        Text(pdf, voucher.StartsAtUtc.ToString("dddd", CultureInfo.InvariantCulture).ToUpperInvariant(),
            55, 423, 10, true, "0.055 0.690 0.705");
        Text(pdf, voucher.StartsAtUtc.ToString("MMMM dd, yyyy", CultureInfo.InvariantCulture),
            55, 393, 23, true, "0.055 0.125 0.255");
        Line(pdf, 330, 365, 330, 440, "0.830 0.855 0.900", 1);
        Text(pdf, "TIME", 357, 423, 9, true, "0.390 0.450 0.555");
        Text(pdf, $"{voucher.StartsAtUtc:HH:mm} - {voucher.EndsAtUtc:HH:mm}",
            357, 393, 22, true, "0.055 0.125 0.255");
        Text(pdf, "UTC", 500, 395, 10, true, "0.055 0.690 0.705");
        Text(pdf, $"Duration: {Math.Max(1, (int)(voucher.EndsAtUtc - voucher.StartsAtUtc).TotalMinutes)} minutes",
            357, 369, 10, false, "0.390 0.450 0.555");

        Card(pdf, 36, 186, 540, 132, "CHECK-IN INFORMATION");
        Bullet(pdf, 54, 274, "Arrive 10 minutes before the scheduled appointment.");
        Bullet(pdf, 54, 249, "Show this voucher or quote the booking reference at reception.");
        Bullet(pdf, 54, 224, "Contact the provider if you need to reschedule or cancel.");
        Text(pdf, "Confirmed at", 406, 276, 8, true, "0.390 0.450 0.555");
        Text(pdf, voucher.ConfirmedAtUtc.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture),
            406, 259, 9, true, "0.055 0.125 0.255");

        Fill(pdf, 36, 126, 540, 40, "0.930 0.950 0.980");
        Text(pdf, "VERIFICATION CODE", 52, 148, 8, true, "0.390 0.450 0.555");
        Text(pdf, voucher.BookingReference, 52, 133, 11, true, "0.055 0.125 0.255");
        Text(pdf, "Securely generated by the CCaaS AI Voice Agent", 302, 137, 9, false, "0.390 0.450 0.555");
        Line(pdf, 36, 94, 576, 94, "0.830 0.855 0.900", 1);
        Text(pdf, "Keep this document for appointment verification.", 36, 72, 8, false, "0.390 0.450 0.555");
        Text(pdf, "Document ID", 412, 72, 8, false, "0.390 0.450 0.555");
        Text(pdf, voucher.BookingId.ToString("N")[..12].ToUpperInvariant(), 480, 72, 8, true, "0.055 0.125 0.255");
        return BuildPdf(pdf.ToString());
    }

    private static void Card(StringBuilder pdf, double x, double y, double width, double height, string title)
    {
        Box(pdf, x, y, width, height, "1 1 1", "0.830 0.855 0.900");
        Text(pdf, title, x + 16, y + height - 23, 9, true, "0.055 0.690 0.705");
        Line(pdf, x + 16, y + height - 32, x + width - 16, y + height - 32, "0.900 0.915 0.945", 1);
    }

    private static void LabelValue(StringBuilder pdf, string label, string value, double x, double y, double valueX)
    {
        Text(pdf, label, x, y, 8, true, "0.390 0.450 0.555");
        Text(pdf, Short(value, 30), valueX, y, 9, true, "0.055 0.125 0.255");
    }

    private static void Bullet(StringBuilder pdf, double x, double y, string value)
    {
        Fill(pdf, x, y + 2, 5, 5, "0.055 0.690 0.705");
        Text(pdf, value, x + 15, y, 9, false, "0.155 0.205 0.300");
    }

    private static void Box(StringBuilder pdf, double x, double y, double width, double height, string fill, string stroke) =>
        pdf.AppendFormat(CultureInfo.InvariantCulture, "q {0} rg {1} RG 0.8 w {2} {3} {4} {5} re B Q\n", fill, stroke, x, y, width, height);

    private static void Fill(StringBuilder pdf, double x, double y, double width, double height, string color) =>
        pdf.AppendFormat(CultureInfo.InvariantCulture, "q {0} rg {1} {2} {3} {4} re f Q\n", color, x, y, width, height);

    private static void Line(StringBuilder pdf, double x1, double y1, double x2, double y2, string color, double width) =>
        pdf.AppendFormat(CultureInfo.InvariantCulture, "q {0} RG {1} w {2} {3} m {4} {5} l S Q\n", color, width, x1, y1, x2, y2);

    private static void Text(StringBuilder pdf, string value, double x, double y, double size, bool bold, string color) =>
        pdf.AppendFormat(CultureInfo.InvariantCulture, "BT {0} rg /{1} {2} Tf 1 0 0 1 {3} {4} Tm ({5}) Tj ET\n",
            color, bold ? "F2" : "F1", size, x, y, Escape(value));

    private static string Short(string value, int length) => value.Length <= length ? value : value[..Math.Max(1, length - 3)] + "...";

    private static byte[] BuildPdf(string commands)
    {
        var stream = Encoding.ASCII.GetBytes(commands);
        var objects = new[]
        {
            "<< /Type /Catalog /Pages 2 0 R >>",
            "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            $"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PageWidth} {PageHeight}] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
            $"<< /Length {stream.Length} >>\nstream\n{commands}endstream",
            "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
            "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"
        };
        using var output = new MemoryStream();
        Write(output, "%PDF-1.4\n");
        var offsets = new List<long> { 0 };
        for (var i = 0; i < objects.Length; i++)
        {
            offsets.Add(output.Position);
            Write(output, $"{i + 1} 0 obj\n{objects[i]}\nendobj\n");
        }
        var xref = output.Position;
        Write(output, $"xref\n0 {objects.Length + 1}\n0000000000 65535 f \n");
        foreach (var offset in offsets.Skip(1)) Write(output, $"{offset:0000000000} 00000 n \n");
        Write(output, $"trailer\n<< /Size {objects.Length + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF");
        return output.ToArray();
    }

    private static string Escape(string value)
    {
        var ascii = string.Concat(value.Select(character => character is >= ' ' and <= '~' ? character : '?'));
        return ascii.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    }

    private static void Write(Stream stream, string value)
    {
        var bytes = Encoding.ASCII.GetBytes(value);
        stream.Write(bytes, 0, bytes.Length);
    }
}
